import type {
  AdminQueueItem,
  CampaignSubmission,
  ContentRightsClaim,
  BillingPlan,
  CreditBalance,
  CreditTransaction,
  ClipCandidate,
  ClipMoment,
  ClipPack,
  EarningEvent,
  EarningsAccount,
  EarningSummary,
  FraudFlag,
  IntegrationCard,
  LedgerEntry,
  MarketplaceCampaign,
  ModerationQueueItem,
  PayoutPlaceholder,
  StripeConnectReadiness,
  WorldJob,
  WorldJobDashboard,
  WorldJobEvent,
  UserEntitlement,
  Quest,
  UGCAsset,
  UserWorldProfile,
} from "./types";

export const mockCampaigns: MarketplaceCampaign[] = [
  {
    id: "camp_001",
    title: "Turn this podcast into 12 TikTok-ready clips",
    description:
      "Need short-form clips with strong hooks, bold captions, and clear CTA. Best submissions should be ready for TikTok and Reels review.",
    buyerName: "Northstar Media",
    sourceType: "clip_pack",
    targetPlatform: "TikTok",
    budget: { amount: 300, currency: "USD" },
    platformFeePercent: 20,
    clipCount: 12,
    deadline: "2026-05-15",
    status: "open",
    requirements: [
      "9:16 vertical format",
      "Burned-in captions",
      "Hook in first 2 seconds",
      "No copyrighted music unless licensed",
    ],
    rightsRequired:
      "Buyer receives usage rights for approved deliverables. Clipper must only submit work they have rights to provide.",
    createdAt: "2026-04-27",
    submissionsCount: 7,
    approvedSubmissionsCount: 2,
  },
  {
    id: "camp_002",
    title: "Create high-retention Shorts from founder interview",
    description:
      "Find the strongest founder moments and package them for YouTube Shorts and Instagram Reels.",
    buyerName: "Signal Launch",
    sourceType: "video_url",
    targetPlatform: "Multi",
    budget: { amount: 500, currency: "USD" },
    platformFeePercent: 20,
    clipCount: 20,
    deadline: "2026-05-22",
    status: "under_review",
    requirements: ["Founder story angle", "Business-growth hooks", "Captions required", "Thumbnail text required"],
    rightsRequired: "Approved submissions may be used across buyer social channels.",
    createdAt: "2026-04-26",
    submissionsCount: 12,
    approvedSubmissionsCount: 4,
  },
];

export const mockSubmissions: CampaignSubmission[] = [
  {
    id: "sub_001",
    campaignId: "camp_001",
    clipperName: "Clipforger Kai",
    title: "The one sentence that changes the whole episode",
    hook: "This is why most creators lose people in the first five seconds.",
    caption: "Start here if you want the clip to actually hold attention.",
    status: "approved",
    estimatedEarnings: { amount: 35, currency: "USD" },
    submittedAt: "2026-04-28",
    reviewNote: "Strong hook. Approved for first test batch.",
  },
  {
    id: "sub_002",
    campaignId: "camp_001",
    clipperName: "Trendseer Nova",
    title: "The mistake everyone makes with short-form clips",
    hook: "Most people cut the wrong part first.",
    caption: "The strongest clip is usually not the loudest moment.",
    status: "revision_requested",
    estimatedEarnings: { amount: 25, currency: "USD" },
    submittedAt: "2026-04-28",
    reviewNote: "Hook is strong, but captions need safe margins.",
  },
];

export const mockEarnings: EarningSummary = {
  estimated: { amount: 180, currency: "USD" },
  pendingReview: { amount: 90, currency: "USD" },
  approved: { amount: 65, currency: "USD" },
  payable: { amount: 40, currency: "USD" },
  paid: { amount: 120, currency: "USD" },
  held: { amount: 25, currency: "USD" },
};

export const mockPlans: BillingPlan[] = [
  {
    planKey: "free",
    name: "Free",
    monthlyPrice: { amount: 0, currency: "USD" },
    monthlyCredits: 25,
    marketplaceFeePercent: 30,
    maxCampaigns: 1,
    maxUgcAssets: 3,
    features: ["Upload-first clipping demo", "Mock fallback", "Basic marketplace preview"],
  },
  {
    planKey: "creator",
    name: "Creator",
    monthlyPrice: { amount: 19, currency: "USD" },
    monthlyCredits: 250,
    marketplaceFeePercent: 25,
    maxCampaigns: 5,
    maxUgcAssets: 25,
    features: ["Creator clip packages", "Campaign-ready exports", "UGC marketplace foundation"],
  },
  {
    planKey: "pro",
    name: "Pro",
    monthlyPrice: { amount: 49, currency: "USD" },
    monthlyCredits: 900,
    marketplaceFeePercent: 20,
    maxCampaigns: 20,
    maxUgcAssets: 100,
    features: ["Higher credit limits", "Advanced campaign workflow", "Lower marketplace fee"],
  },
  {
    planKey: "agency",
    name: "Agency",
    monthlyPrice: { amount: 149, currency: "USD" },
    monthlyCredits: 3500,
    marketplaceFeePercent: 15,
    maxCampaigns: 100,
    maxUgcAssets: 500,
    features: ["Agency-scale campaigns", "Priority review foundation", "Team-ready operating model"],
  },
];

export const mockEntitlement: UserEntitlement = {
  userId: "demo_user",
  planKey: "creator",
  status: "active",
  source: "demo",
  createdAt: "2026-04-28T09:00:00-04:00",
  updatedAt: "2026-04-28T09:00:00-04:00",
};

export const mockCreditBalance: CreditBalance = {
  userId: "demo_user",
  balance: 184,
  monthlyGrant: 250,
  usedThisPeriod: 66,
  periodStart: "2026-04-01T00:00:00-04:00",
  updatedAt: "2026-04-28T14:00:00-04:00",
};

export const mockCreditTransactions: CreditTransaction[] = [
  {
    id: "credtx_001",
    userId: "demo_user",
    transactionType: "grant",
    amount: 250,
    balanceAfter: 250,
    reason: "Creator monthly grant.",
    sourceType: "plan",
    sourceId: "creator",
    createdAt: "2026-04-01T00:00:00-04:00",
  },
  {
    id: "credtx_002",
    userId: "demo_user",
    transactionType: "spend",
    amount: -66,
    balanceAfter: 184,
    reason: "Generated clip package.",
    sourceType: "generation",
    sourceId: "job_001",
    createdAt: "2026-04-28T10:00:00-04:00",
  },
];

export const mockEarningsAccount: EarningsAccount = {
  userId: "demo_user",
  estimatedAmount: 180,
  pendingReviewAmount: 90,
  approvedAmount: 65,
  payableAmount: 0,
  paidAmount: 0,
  heldAmount: 25,
  currency: "USD",
  updatedAt: "2026-04-28T14:00:00-04:00",
};

export const mockEarningEvents: EarningEvent[] = [
  {
    id: "earn_001",
    userId: "demo_user",
    sourceType: "submission",
    sourceId: "sub_001",
    amount: 35,
    platformFeeAmount: 7,
    netAmount: 28,
    currency: "USD",
    status: "approved",
    note: "Approved marketplace earning. Payout remains disabled.",
    createdAt: "2026-04-28T11:00:00-04:00",
  },
];

export const mockPayoutPlaceholders: PayoutPlaceholder[] = [
  {
    id: "payout_001",
    userId: "demo_user",
    amount: 28,
    currency: "USD",
    status: "blocked",
    blockedReason: "Real payouts are disabled until Stripe Connect and payout controls are complete.",
    createdAt: "2026-04-28T12:00:00-04:00",
    updatedAt: "2026-04-28T12:00:00-04:00",
  },
];

export const mockStripeReadiness: StripeConnectReadiness = {
  enabled: false,
  ready: false,
  requiredEnvVars: ["STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET", "STRIPE_CONNECT_CLIENT_ID"],
  missingEnvVars: ["STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET", "STRIPE_CONNECT_CLIENT_ID"],
  blockers: [
    "Stripe Connect transfers are not implemented.",
    "KYC/tax onboarding is not implemented.",
    "Dispute and fraud holds are placeholders only.",
  ],
  note: "Stripe Connect is readiness-only. No real payouts or transfers are performed.",
};

export const mockJobs: WorldJob[] = [
  {
    id: "job_001",
    ownerUserId: "demo_user",
    jobType: "upload_processing",
    status: "running",
    priority: "normal",
    progressPercent: 45,
    title: "Process upload: founder_interview.mp4",
    description: "Probe media metadata, scan file, and prepare source for clipping.",
    sourceId: "upload_001",
    targetType: "upload",
    targetId: "upload_001",
    inputJson: "{}",
    outputJson: "{}",
    maxAttempts: 3,
    attemptCount: 1,
    startedAt: "2026-04-28T12:55:00-04:00",
    createdAt: "2026-04-28T12:50:00-04:00",
    updatedAt: "2026-04-28T12:56:00-04:00",
  },
  {
    id: "job_002",
    ownerUserId: "demo_user",
    jobType: "clip_generation",
    status: "queued",
    priority: "high",
    progressPercent: 0,
    title: "Generate 10 creator clips",
    description: "Create clip candidates from uploaded source.",
    sourceId: "upload_001",
    targetType: "campaign",
    targetId: "camp_001",
    inputJson: "{}",
    outputJson: "{}",
    maxAttempts: 3,
    attemptCount: 0,
    createdAt: "2026-04-28T13:00:00-04:00",
    updatedAt: "2026-04-28T13:00:00-04:00",
  },
];

export const mockJobEvents: WorldJobEvent[] = [
  {
    id: "jobevt_001",
    jobId: "job_001",
    eventType: "job_created",
    message: "Job created and queued.",
    statusAfter: "queued",
    progressPercent: 0,
    metadataJson: "{}",
    createdAt: "2026-04-28T12:50:00-04:00",
  },
  {
    id: "jobevt_002",
    jobId: "job_001",
    eventType: "job_updated",
    message: "Job status/progress updated.",
    statusBefore: "queued",
    statusAfter: "running",
    progressPercent: 45,
    metadataJson: "{}",
    createdAt: "2026-04-28T12:56:00-04:00",
  },
];

export const mockJobDashboard: WorldJobDashboard = {
  queued: 1,
  running: 1,
  succeeded: 4,
  failed: 0,
  retrying: 0,
  cancelled: 0,
  recentJobs: mockJobs,
};

export const mockClipPacks: ClipPack[] = [
  {
    id: "clippack_001",
    ownerUserId: "demo_user",
    sourceId: "upload_001",
    transcriptId: "transcript_001",
    title: "Founder interview clip pack",
    targetPlatform: "TikTok",
    desiredClipCount: 10,
    status: "detecting_moments",
    selectedCandidateIds: ["clipcand_001"],
    jobId: "job_002",
    createdAt: "2026-04-28T13:00:00-04:00",
    updatedAt: "2026-04-28T13:02:00-04:00",
  },
];

export const mockClipMoments: ClipMoment[] = [
  {
    id: "moment_001",
    ownerUserId: "demo_user",
    sourceId: "upload_001",
    transcriptId: "transcript_001",
    startSeconds: 12,
    endSeconds: 42,
    transcriptExcerpt: "Most creators cut the wrong moment first.",
    momentType: "insight",
    reason: "Strong hook and creator pain.",
    confidence: 88,
    createdAt: "2026-04-28T13:04:00-04:00",
  },
];

export const mockClipCandidates: ClipCandidate[] = [
  {
    id: "clipcand_001",
    ownerUserId: "demo_user",
    sourceId: "upload_001",
    transcriptId: "transcript_001",
    momentId: "moment_001",
    title: "Most creators cut the wrong part first",
    hook: "Most creators cut the wrong part first.",
    caption: "The strongest clip starts where the tension begins.",
    startSeconds: 12,
    endSeconds: 42,
    targetPlatform: "TikTok",
    status: "scored",
    scoreTotal: 83,
    scoreHook: 78,
    scoreRetention: 84,
    scoreClarity: 95,
    scoreEmotion: 24,
    scoreShareability: 60,
    scorePlatformFit: 86,
    riskNotes: ["Review source rights and context before publishing."],
    createdAt: "2026-04-28T13:05:00-04:00",
    updatedAt: "2026-04-28T13:05:00-04:00",
  },
];

export const mockLedger: LedgerEntry[] = [
  {
    id: "led_001",
    type: "clip_generated",
    label: "Generated first clip pack",
    xp: 50,
    reputation: 5,
    createdAt: "2026-04-28T10:00:00-04:00",
    status: "recorded",
    referenceId: "job_001",
  },
  {
    id: "led_002",
    type: "campaign_created",
    label: "Created marketplace campaign from clip pack",
    xp: 75,
    createdAt: "2026-04-28T10:15:00-04:00",
    status: "recorded",
    referenceId: "camp_001",
  },
  {
    id: "led_003",
    type: "earning_approved",
    label: "Submission approved",
    amount: { amount: 35, currency: "USD" },
    xp: 100,
    reputation: 10,
    createdAt: "2026-04-28T11:00:00-04:00",
    status: "recorded",
    referenceId: "sub_001",
  },
];

export const mockWorldProfile: UserWorldProfile = {
  id: "profile_001",
  displayName: "LWA Founder",
  className: "Signalwright",
  faction: "The Signalwrights",
  level: 7,
  xp: 740,
  nextLevelXp: 1000,
  creatorReputation: 80,
  clipperReputation: 45,
  marketplaceReputation: 60,
  titles: ["First Signal", "Campaign Hunter"],
  badges: [
    {
      id: "badge_001",
      name: "First Signal",
      tier: "common",
      description: "Generated your first LWA clip pack.",
      lore: "Every empire begins with a signal.",
      unlockedAt: "2026-04-28",
    },
    {
      id: "badge_002",
      name: "Campaign Hunter",
      tier: "rare",
      description: "Created or completed a marketplace campaign.",
      lore: "The market moves for those who can read the noise.",
      unlockedAt: "2026-04-28",
    },
  ],
  relics: [
    {
      id: "relic_001",
      name: "Gold Thread Fragment",
      tier: "epic",
      description: "A relic tied to approved marketplace work.",
      lore: "It appears only when creation becomes value.",
      unlockedAt: "2026-04-28",
    },
  ],
};

export const mockQuests: Quest[] = [
  {
    id: "quest_001",
    title: "Generate your first clip pack",
    description: "Use the AI engine to turn one source into short-form assets.",
    category: "clipping",
    progress: 1,
    goal: 1,
    rewardXp: 50,
    status: "completed",
  },
  {
    id: "quest_002",
    title: "Create your first marketplace campaign",
    description: "Turn a clip pack into a buyer-funded job.",
    category: "marketplace",
    progress: 1,
    goal: 1,
    rewardXp: 75,
    status: "completed",
  },
  {
    id: "quest_003",
    title: "Submit your first campaign clip",
    description: "Submit work to an open campaign and enter review.",
    category: "marketplace",
    progress: 0,
    goal: 1,
    rewardXp: 100,
    status: "available",
  },
];

export const mockUgcAssets: UGCAsset[] = [
  {
    id: "ugc_001",
    creatorUserId: "demo_user",
    title: "Gold Thread Hook Pack",
    assetType: "Hook Pack",
    description: "Short-form hooks for founders, creators, agencies, and marketplace campaigns.",
    price: { amount: 19, currency: "USD" },
    status: "pending_review",
    moderationStatus: "pending",
    rightsConfirmed: true,
    licenseSummary: "Buyer receives usage rights for content templates only.",
    createdAt: "2026-04-28",
  },
  {
    id: "ugc_002",
    creatorUserId: "demo_user",
    title: "Signal Realms Quest Template",
    assetType: "Quest Template",
    description: "A reusable quest structure that turns real creator actions into RPG progression.",
    price: { amount: 29, currency: "USD" },
    status: "draft",
    moderationStatus: "pending",
    rightsConfirmed: true,
    licenseSummary: "Template license for use inside LWA Worlds.",
    createdAt: "2026-04-28",
  },
];

export const mockModerationQueue: ModerationQueueItem[] = [
  {
    id: "mod_001",
    targetType: "ugc_asset",
    targetId: "ugc_001",
    submittedBy: "demo_user",
    status: "pending",
    reason: "UGC asset submitted for marketplace review.",
    automatedScore: 12,
    createdAt: "2026-04-28T12:00:00-04:00",
  },
  {
    id: "mod_002",
    targetType: "campaign",
    targetId: "camp_001",
    submittedBy: "demo_user",
    status: "flagged",
    reason: "Campaign budget and source rights need admin review.",
    automatedScore: 31,
    createdAt: "2026-04-28T12:20:00-04:00",
  },
];

export const mockFraudFlags: FraudFlag[] = [
  {
    id: "fraud_001",
    userId: "demo_user",
    targetType: "submission",
    targetId: "sub_002",
    flagType: "duplicate_clip_risk",
    status: "open",
    severity: "medium",
    evidence: "Submission appears similar to another clip package.",
    createdAt: "2026-04-28T12:45:00-04:00",
  },
];

export const mockRightsClaims: ContentRightsClaim[] = [
  {
    id: "rights_001",
    claimantName: "Rights Holder Demo",
    claimantEmail: "rights@example.com",
    targetType: "ugc_asset",
    targetId: "ugc_001",
    claimSummary: "Demo rights claim for review workflow.",
    status: "open",
    createdAt: "2026-04-28T13:00:00-04:00",
  },
];

export const mockIntegrations: IntegrationCard[] = [
  {
    id: "int_openai",
    name: "OpenAI",
    category: "ai",
    status: "configured",
    description: "Hooks, captions, ranking, packaging, structured outputs.",
    envVars: ["OPENAI_API_KEY"],
  },
  {
    id: "int_anthropic",
    name: "Anthropic Claude",
    category: "ai",
    status: "not_configured",
    description: "Long transcript analysis, strategy, and consistency checks.",
    envVars: ["ANTHROPIC_API_KEY"],
  },
  {
    id: "int_youtube",
    name: "YouTube Data API",
    category: "social",
    status: "mocked",
    description: "Video and channel metadata for future source enrichment.",
    envVars: ["YOUTUBE_API_KEY", "GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  {
    id: "int_twitch",
    name: "Twitch",
    category: "social",
    status: "not_configured",
    description: "Streamer, VOD, and clip metadata for creator campaigns.",
    envVars: ["TWITCH_CLIENT_ID", "TWITCH_CLIENT_SECRET"],
  },
  {
    id: "int_whop",
    name: "Whop",
    category: "payments",
    status: "mocked",
    description: "Paid access, memberships, founder pass, and subscriptions.",
    envVars: ["WHOP_API_KEY", "WHOP_WEBHOOK_SECRET"],
  },
  {
    id: "int_stripe",
    name: "Stripe Connect",
    category: "payments",
    status: "disabled",
    description: "Future marketplace payments, fees, and payouts.",
    envVars: ["STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET"],
    adminOnly: true,
  },
  {
    id: "int_wallet",
    name: "Wallet / Future LWA Chain",
    category: "blockchain",
    status: "disabled",
    description: "Future optional proof, badges, and collectible ownership.",
    envVars: ["NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID"],
  },
];

export const mockAdminQueue: AdminQueueItem[] = [
  {
    id: "queue_001",
    type: "campaign_review",
    title: "Founder interview shorts campaign pending review",
    status: "open",
    priority: "high",
    createdAt: "2026-04-28T09:10:00-04:00",
    owner: "Marketplace",
  },
  {
    id: "queue_002",
    type: "submission_review",
    title: "Caption safe-margin revision requested",
    status: "in_review",
    priority: "medium",
    createdAt: "2026-04-28T10:20:00-04:00",
    owner: "Review",
  },
  {
    id: "queue_003",
    type: "payout_review",
    title: "$65 approved earnings awaiting payout eligibility",
    status: "open",
    priority: "medium",
    createdAt: "2026-04-28T11:00:00-04:00",
    owner: "Payouts",
  },
];
